### ISSUE TITLE
arm-none-eabi-gcc fails on os x 10.9

### ISSUE THREAD

**Issue by ayonix** [plietar/homebrew-stm32#2]
`brew tap plietar/stm32; brew install arm-none-eabi-gcc` gives: 

```
==> ../configure --target=arm-none-eabi --prefix=/usr/local/Cellar/arm-none-eabi-gcc/4.7.2 --enable-multilib --with-newlib --with-gnu-as --with-gnu-ld --disable-nls --disable-shared --disable-threads --with-headers=newlib/libc/include --disable-libssp --disable-libstdcx 
==> make 
configure: error: in `/private/tmp/arm-none-eabi-gcc-MvKk/gcc-4.7.2/build/gcc': 
configure: error: C++ preprocessor "/lib/cpp" fails sanity check 
See `config.log' for more details. 
make[1]: *** [configure-gcc] Error 1 
make: *** [all] Error 2
```

**Comment by plietar** [comment]
It works fine for me on 10.9
Do you have a `/lib/cpp` on your computer ? I don't.

Try `brew install arm-none-eabi-gcc --with-gcc`

**Comment by ayonix** [comment]
`ls: /lib/cpp: No such file or directory`
`--with-gcc` has the same result.

**Comment by plietar** [comment]
Try with `--verbose`

**Comment by ayonix** [comment]
The logs when I did `brew install arm-none-eabi-gcc --with-gcc --verbose`

https://gist.github.com/ayonix/7322212

**Comment by nitsky** [comment]
I have the exact same issue here. Any ideas?

**Comment by plietar** [comment]
Can you try and install a "real" gcc, eg from package `apple-gcc4.2`

**Comment by nitsky** [comment]
just tried that, same result, there must still be something I'm missing

**Comment by plietar** [comment]
Can you edit the formula, and add a "--build=x86_64-apple-darwin12.5.0" in the args list.
If that doesn't work try with 13.0.0 instead of 12.5.0.

**Comment by nitsky** [comment]
that didn't fix it, any other ideas?

**Comment by kerker00** [comment]
i have the some problem
i had tried everything listed above.

**Comment by nitsky** [comment]
I was unable to get this formula working so I made my own which works fine. Check it out here: https://github.com/nitsky/homebrew-stm32

**Comment by plietar** [comment]
I've just made major changes to the formulae.
Closing this unless someone encounters the problem again.
